[package]
name = "broadcaster"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
env_logger = "0.11.8"
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.140"
log = "0.4"