[package]
name = "jwt-lib"
version = "0.1.0"
edition = "2021"



[dependencies]
utils = { path = "../utils" } 
chrono = "0.4.34"
jsonwebtoken = "9.2.0"
serde = { version = "1.0.197", features = ["derive"] }